# Generated by Django 2.2.2 on 2020-02-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
